# Generated by Django 4.2.5 on 2023-09-30 13:15

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="JobListing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_created=True, auto_now=True)),
                ("job_id", models.CharField(max_length=500)),
                ("title", models.CharField(max_length=250)),
                ("company", models.CharField(max_length=255)),
                ("date", models.DateField()),
                ("img", models.CharField(max_length=500)),
                ("source", models.CharField(max_length=250)),
            ],
        ),
    ]
