# Generated by Django 4.2.5 on 2023-09-30 14:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("jobs", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="joblisting",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
