# Generated by Django 4.2.5 on 2023-09-30 16:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("jobs", "0002_alter_joblisting_created_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="joblisting",
            name="tags",
            field=models.JSONField(null=True),
        ),
    ]
