# Generated by Django 4.2.5 on 2023-09-30 16:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("jobs", "0003_joblisting_tags"),
    ]

    operations = [
        migrations.AddField(
            model_name="joblisting",
            name="location",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
